<?php
/**
 * @file
 * alpha_module.field_base.inc
 */

function alpha_module_default_field_base_assets() {
  /*
  $field_bases = array();

  // Exported field_base: 'field_article_body'
  $field_bases['field_article_body'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_article_body',
    'indexes' => array(
      'format' => array(
        0 => 'format',
      ),
    ),
    'locked' => 0,
    'module' => 'text',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'text_long',
  );

  return $field_bases;*/
}
