<?php
/**
 * @file
 * alpha_module.field_instance.inc
 */


function alpha_module_default_field_instance_assets() {
  /*$field_instances = array();

  // Exported field_instance: 'field_collection_item-field_article_quote-field_article_quote_author'
  $field_instances['field_collection_item-field_article_quote-field_article_quote_author'] = array(
    'bundle' => 'field_article_quote',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'field_collection_item',
    'field_name' => 'field_article_quote_author',
    'label' => 'Author',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 42,
    ),
  );
  // Translatables
  // Included for use with string extractors like potx.
  t('Author');

  return $field_instances;*/
}
